openapi: 3.0.0
info:
  title: Todo API
  description: A simple API for managing todo items
  version: 1.0.0

paths:
  /todos:
    get:
      summary: Get all todo items
      operationId: getAllTodos
      responses:
        '200':
          description: A list of todo items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'
    post:
      summary: Create a new todo item
      operationId: createTodo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItemPayload'
      responses:
        '201':
          description: The newly created todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoError'

  /todos/{id}:
    parameters:
      - name: id
        in: path
        description: ID of the todo item to retrieve
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get a todo item by ID
      operationId: getTodoById
      responses:
        '200':
          description: The requested todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '404':
          description: Todo item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoError'
    patch:
      summary: Update a todo item by ID
      operationId: updateTodoById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoItemPayload'
      responses:
        '200':
          description: The updated todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoError'
        '404':
          description: Todo item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoError'
    delete:
      summary: Delete a todo item by ID
      operationId: deleteTodoById
      responses:
        '204':
          description: Todo item successfully deleted
        '404':
          description: Todo item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoError'

components:
  schemas:
    TodoItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier for the todo item
        title:
          type: string
          description: The title of the todo item
          maxLength: 10
        completed:
          type: boolean
          description: Whether the todo item is completed or not
      required:
        - id
        - title
        - completed

    TodoItemPayload:
      type: object
      properties:
        title:
          type: string
          description: The title of the new todo item
          maxLength: 10
      required:
        - title

    UpdateTodoItemPayload:
      type: object
      properties:
        completed:
          type: boolean
          description: Whether the todo item is completed or not
      required:
        - completed
          
    TodoError:
      type: object
      properties:
        code:
          type: integer
          description: A code that represents the type of TodoError
        message:
          type: string
          description: A human-readable TodoError message
      required:
        - code
        - message
